### PR TITLE
fix: support startTime/endTime parameters and correct database column

### LINKED ISSUE #491: StartTime property not working
**Describe the bug**
According to openapi schema https://github.com/formancehq/ledger/blob/main/openapi/v1.yaml#L516

We should use `startTime` but in code https://github.com/formancehq/ledger/blob/main/internal/api/v1/controllers_transactions.go#L59 is not supported.

Another thing is 
```
if startTime := r.URL.Query().Get("start_time"); startTime != "" {
		clauses = append(clauses, query.Gte("date", startTime))
	}
```

Column `date` not exists

**To Reproduce**
Make request to transaction with time frames

**Expected behavior**
Transactions are filtered

**Environment (please complete the following information):**
 Main master of ledger

### PR DESCRIPTION
**Pull request by rohanxyzg**
Fixes #491

- Add support for new `startTime` parameter as specified in OpenAPI v1.yaml
- Add support for new `endTime` parameter (similar issue)
- Maintain backward compatibility with deprecated `start_time`/`end_time`
- Fix incorrect database column reference from `date` to `timestamp`
- Query now correctly filters transactions by timestamp range

Changes:
- Support both camelCase (startTime/endTime) and snake_case (start_time/end_time) parameters
- Use correct `timestamp` column name matching database schema
- Prioritize new parameter names over deprecated ones

### CODE REVIEW

File: internal/api/v1/controllers_transactions.go [hunk 1]
```diff
@@ -59,11 +59,22 @@ func buildGetTransactionsQuery(r *http.Request) query.Builder {
 		clauses = append(clauses, query.Lt("id", after))
 	}
 
-	if startTime := r.URL.Query().Get("start_time"); startTime != "" {
-		clauses = append(clauses, query.Gte("date", startTime))
+	// Support both startTime (new) and start_time (deprecated) parameters
+	startTime := r.URL.Query().Get("startTime")
```
Comment (fguery) [inline internal/api/v1/controllers_transactions.go:63]: Good catch, thanks for this!
Could you also update the tests in `controllers_transactions_count_test` and `controllers_transactions_list_test` ?

**Review by fguery — APPROVED** [review]
